### ISSUE TITLE
use array

### ISSUE THREAD

**Issue by dittyBox** [minholeelog/practice-js#1]
const app = document.querySelector("#app");
const numberBtn = document.querySelectorAll(".number-btn");
const operatorBtn = document.querySelectorAll(".operator-btn");
const clearBtn = document.querySelector(".clear-btn");
const resultBtn = document.querySelector(".result-btn");
const input = document.querySelector(".calc-result");
const display = document.querySelector(".calc-display");

let calculationBoolean = false;
let ary = [];

function aryCalculation(aryData) {
  if (aryData.length === 0) return;
  let calculationStr = eval(aryData.join(""));
  return calculationStr;
}

function setDisplay(aryData) {
  display.value = aryData.join(" ");
}

function handleNumberBtn() {
  let currentNumber = this.innerText;
  if (input.value === "0" && currentNumber === 0) return;
  input.value = calculationBoolean || input.value === "0" ? "" : input.value;
  input.value = `${input.value + currentNumber}`;
  calculationBoolean = false;
  console.log(calculationBoolean);
}

function handleOperatorBtn() {
  if (ary.length === 0 && input.value === "0") return;
  if (ary.length > 0 && calculationBoolean) {
    ary.pop();
    ary.push(this.innerText);
    setDisplay(ary);
    return;
  }
  if (calculationBoolean) return;
  ary.push(input.value);
  ary.push(this.innerText);
  calculationBoolean = true;
  setDisplay(ary);
  input.value = aryCalculation(ary);
  console.log(calculationBoolean);
}

function handleClear() {
  input.value = "0";
  ary = [];
  setDisplay(ary);
}

function handleResult() {
  if (calculationBoolean === false && ary.length > 0) {
    ary.push(input.value);
  }
  console.log(ary);
  if (ary.length > 1) {
    if (calculationBoolean) ary.pop();
    input.value = aryCalculation(ary);
    console.log(ary);
  }
  setDisplay(ary);
  ary = [];
  calculationBoolean = true;
}

Array.from(numberBtn).forEach((item) => {
  item.addEventListener("click", handleNumberBtn);
});

Array.from(operatorBtn).forEach((item) => {
  item.addEventListener("click", handleOperatorBtn);
});

clearBtn.addEventListener("click", handleClear);
resultBtn.addEventListener("click", handleResult);

**Comment by minholeelog** [comment]
배열을 사용하는 방법이 있었네요. 
올려주신 코드 보고 다시 고민해보겠습니다.
감사합니다 :)
